version: '3'
services:
  db:
    container_name: ab_mariadb
    image: mariadb:latest
    restart: always
    ports:
      - '23306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd
    volumes:
      - ./_cache/data:/var/lib/mysql:delegated
      - ../.db:/docker-entrypoint-initdb.d:cached
    command: mysqld --skip-name-resolve --character-set-server=utf8 --collation-server=utf8_unicode_ci
  backend:
    container_name: ab_nginx_backend
    image: dmstr/php-yii2:7.2-fpm-4.0-alpha5-alpine-nginx
    restart: always
    volumes:
      - ./_host-volumes/backend/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./_cache/main/backend/log/nginx:/var/log/nginx:cached
      - ./_cache/composer:/root/.composer:cached
      - ..:/app:delegated
    links:
      - db
  frontend:
    container_name: ab_nginx_frontend
    image: dmstr/php-yii2:7.2-fpm-4.0-alpha5-alpine-nginx
    restart: always
    volumes:
      - ./_host-volumes/frontend/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./_cache/frontend/var/log/nginx:/var/log/nginx:cached
      - ./_cache/composer:/root/.composer:cached
      - ..:/app:delegated
    links:
      - db
  proxy:
    container_name: ab_nginx_proxy
    image: dmstr/php-yii2:7.2-fpm-4.0-alpha5-alpine-nginx
    restart: always
    volumes:
      - ./_host-volumes/main/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./_cache/main/var/log/nginx:/var/log/nginx:cached
      - ./_cache/composer:/root/.composer:cached
    ports:
      - '8090:80'
      - '8091:81'
    links:
      - frontend
      - backend